management.health.jms.enabled: false

rest:
  connectionTimeout: 5000
  readTimeout: 5000
  maxConnectionsTotal: 50
  maxConnectionsPerRoute: 50

springdoc:
  show-actuator: true

wrapper-config:
  wrappers:
    -
      destination: "test1"
      input:
        type: "HTTP"
        url: "http://localhost:8080/test"
      output:
        type: "JMS"
        url: "tcp://localhost:8080"
        channel: "test1"
    -
      destination: "test2"
      input:
        type: "HTTP"
        url: "http://localhost:8080/test"
      output:
        type: "JMS"
        url: "tcp://localhost:8080"
        channel: "test1"

