rest:
  connectionTimeout: 5000
  readTimeout: 5000
  maxConnectionsTotal: 50
  maxConnectionsPerRoute: 50

springdoc:
  show-actuator: true

wrapper-config:
  wrappers:
    -
      channelName: "test1"
      inputChannel: "HTTP"
      outputChannel: "JMS"
    -
      channelName: "test2"
      inputChannel: "HTTP"
      outputChannel: "JMS"

